const CREATING_STORY = 1;
const GENERATING_FACTS = 2;
const IDENTIFYING_HIPOTESYS = 3;
const RESEARCHING = 4;
const RESOLVING_PROBLEM = 5;
const ABSTRACTING = 6;
const FINISHED = 7;

module.exports = {
  CREATING_STORY : CREATING_STORY,
  GENERATING_FACTS : GENERATING_FACTS,
  IDENTIFYING_HIPOTESYS : IDENTIFYING_HIPOTESYS,
  RESEARCHING : RESEARCHING,
  RESOLVING_PROBLEM : RESOLVING_PROBLEM,
  ABSTRACTING : ABSTRACTING,
  FINISHED: FINISHED
};
