const CREATING_STORY = 1;
const IDENTIFYING_HIPOTESYS = 2;
const GENERATING_FACTS = 3;
const IDENTIFYING_DISABLED_KNOWLEDGES = 4;
const ABSTRACTING = 5;

module.exports = {
    CREATING_STORY = CREATING_STORY,
    IDENTIFYING_HIPOTESYS = IDENTIFYING_HIPOTESYS,
    GENERATING_FACTS = GENERATING_FACTS,
    IDENTIFYING_DISABLED_KNOWLEDGES = IDENTIFYING_DISABLED_KNOWLEDGES,
    ABSTRACTING = ABSTRACTING
};
