const FACT = 2;
const HIPOTESYS = 3;
const DISABLED_KNOWLEDGE = 4;
const NEW_KNOWLEDGE = 5;

module.exports = {
  FACT : FACT,
  HIPOTESYS : HIPOTESYS,
  DISABLED_KNOWLEDGE : DISABLED_KNOWLEDGE,
  NEW_KNOWLEDGE : NEW_KNOWLEDGE
};
